from sqlalchemy import Column, String, DateTime, ForeignKey
from sqlalchemy.dialects.postgresql import UUID, JSON
from sqlalchemy.orm import relationship
from datetime import datetime
import uuid

from ..database import Base


class AnalysisReport(Base):
    """Analysis reports generated by AI"""

    __tablename__ = "analysis_reports"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)

    # Report metadata
    report_type = Column(String(50), nullable=False, index=True)  # daily, weekly, monthly, custom
    period_start = Column(DateTime, nullable=False, index=True)
    period_end = Column(DateTime, nullable=False, index=True)

    # Analysis data (stored as JSON)
    insights = Column(JSON, nullable=True)  # Key insights from the analysis
    recommendations = Column(JSON, nullable=True)  # AI-generated recommendations
    time_distribution = Column(JSON, nullable=True)  # Category-wise time distribution
    productivity_analysis = Column(JSON, nullable=True)  # Productivity trends
    location_analysis = Column(JSON, nullable=True)  # Location-based insights

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    user = relationship("User", back_populates="analysis_reports")

    def __repr__(self):
        return f"<AnalysisReport(id={self.id}, type={self.report_type}, period={self.period_start} to {self.period_end})>"
